✨ Posting 피드면 TableView 생성 (이모티콘 선택 기능 포함)
mash-up-kr/DamgleDamgle_iOS pull request #2
Opened 2022-07-10 12:50 UTC by cws653

## 이슈 링크
1. 초기 RxSwift + MVVM 기술스택을 적용해서 프로젝트를 진행하려고 했으나, 기술 적용을 위한 레퍼런스가 부족하여 정해진 시간내에 프로젝트
   를 완성하기에 어려움이 있어, 향후 1차 배포 이후 RxSwift를 별도로 적용하기로 결정함

## 작업 내용
1. 스토리보드를 활용하여 View 기능 설정 및 레이아웃을 잡아줌
2. MVVM 아키텍처를 적용하여 View-ViewModel-DomainModel 역할을 분리시킴
3. Posting 피드면을 기능을 TableView을 사용하여 구현함
4. TableViewCell 내부에 Icon 클릭시 선택된 데이터를 ViewModel에 전달하도록 로직 구현함
5. TableViewCell 내부 Icon 버튼 클릭에 따른 View 애니메이션 기능 구현함
6. 다음주내로 Icon 버튼 클릭에 따른 TableViewCell 내부 IconImage 변경 및 상단 인기순, 날짜순 SortingButton 클릭시 이벤트 구현 예정

### 스크린샷
https://user-images.githubusercontent.com/45356844/178145303-b345287e-45be-4f12-9809-88defb53a116.mp4

## To 리뷰어 (참고사항)
현업 경험이 없어 클린코드에 대한 지식 및 코드를 효율적으로 짜는 부분이 부족하다고 생각이 된다.
이에 내용을 확인하고 수정 보완이 필요한 부분이 있으면 리뷰로 남겨주면 고마울 것 같다.

2022-07-12 09:46 UTC, lina0322 commented
컨플릭 해결 먼저 해주세요~ PR 보낼때 컨플릭은 항상 해결하고 올려주는 습관이 필요합니당🙏

2022-07-12 09:48 UTC, lina0322 commented
1. 파일이 너무 많아요. 쪼개서 올려주세요
2. 커밋 단위 좀 더 작게 해주세요. 

이슈를 작게 나누고, 기능을 세세하게 나눠야 커밋하기도 PR하기도 좋아요.
모든 기능들은 되도록 독립적인게 좋으니, 작은 기능별로 따로따로 작업할 수 있도록 노력해주세용~

2022-07-12 10:05 UTC, lina0322 requested changes
대략적으로만 남겼으니까, 궁금한거 있으면 따로 우리 카톡방에 말해주기!🙏

2022-07-12 10:05 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    var viewModel = PostingViewModel()
외부에 공개되도 괜찮나용?

2022-07-12 10:05 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    }
스토리보드에서도 가능한데, 코드를 선호하나요~

2022-07-12 10:05 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +            print(iconButton)
print 제거해주세용~ 꼭 필요하면 log나 debugPrint 사용해주세요

2022-07-12 15:05 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +            let iconsButtons = [self.likeButton, self.angryButton, self.amazingButton, self.sadButton, self.bestButton]
처음부터 배열로 저장해서 코드를 수정해놓도록 하겠습니다!

2022-07-12 15:05 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    }
tag를 활용한 레퍼런스가 있으면 참고해서 수정해놓도록 하겠습니다~

2022-07-12 15:05 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    var viewModel = PostingViewModel()
접근제한자 명시해놓도록 하겠습니다!

2022-07-12 15:05 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +class PostingMainViewController: UIViewController {
옙 반영하도록 하겠습니다.

2022-07-12 15:05 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    }
코드를 통해서 보통 설정해주었는데 스토리보드로 해놓도록 하겠습니다.

2022-07-12 15:05 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +            print(iconButton)
옙 알겠습니다!

2022-07-13 10:03 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    static let identifier = "PostTableViewCell"
이거 제가 적용시켜놓을게요 이번 PR에서 스킵합시다!

2022-07-13 10:04 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    @IBOutlet private weak var bestButtonXPointConstraint: NSLayoutConstraint!
요건 이번에는 이미 구현 끝나서, 2차 배포하기 전에 리팩토링 할 시간 있으면 같이 리팩토링 해봅시당!

2022-07-13 10:04 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +        let stackConstraints: [(NSLayoutConstraint, iconsButton)] = [(self.likeButtonXPointConstraint, iconsButton.likeButton), (self.angryButtonXPointConstraint, iconsButton.angryButton), (self.amaz
절절히..? 적절히가 아니라..?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-07-13 10:06 UTC, lina0322 commented
수정사항도 있으면 푸시 따로 해주세욥!🙏

2022-07-13 14:37 UTC, merged