✨ Icons 버튼 클릭에 따라 이미지 그려주는 로직 및 UI 구현
mash-up-kr/DamgleDamgle_iOS pull request #28
Opened 2022-07-26 15:33 UTC by cws653

## 이슈 링크 
![Simulator Screen Shot - iPhone 12 - 2022-07-24 at 17 29 09](https://user-images.githubusercontent.com/45356844/181046203-93c3f108-5237-41c0-a381-4ec8e7800caa.png)

https://user-images.githubusercontent.com/45356844/181046992-244e3534-cb32-4689-8ee1-822098f9d7a9.mp4

상기 스크린샷 및 영상을 보면 IconsView가 초기 셋팅될 때 frame 값이 SuperView Frame 바깥으로 벗어나는 이슈가 발생하고 있음.
코드 및 오토레이아웃을 점검해본 결과, 문제 발생 원인을 찾을 수 없어 이슈 항목에 넣어놓았음.

## 작업 내용
Icons 버튼 클릭에 따라 Icons 이미지 추가 및 라벨 count값 변화되도록 설정 (Mock 데이터를 활용하여 로직 구현)

## To 리뷰어 (참고사항)
- 수정이 필요한 부분 알려주시면 수정하도록 하겠습니다.
- 이슈사항 원인을 알고 싶습니다...

2022-07-27 15:18 UTC, lina0322 requested changes
신딜리게이트 수정한거는 제거헤주시고, 나머지는 다음에 적용해도 괜찮아요.
지금 이슈 발생하는거 PR로는 저도 지금 확인이 어려울거같아서 QA때 함께 보면서 수정해보도록 합시당.
일단 만들 수 있는거 먼저 만들자, 사소한건 나중에 수정하는걸로ㄱ

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RotatableImageView.swift
> +class RotatableImageView: UIImageView {
다른곳에 상속될 일이 있는건가용?

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RoundLabel.swift
> +class RoundLabel: UILabel {
이것두!

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RoundLabel.swift
> +        self.layer.masksToBounds = true
린트에 self 제거 넣을 수 잇나용?

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/ManyIconsView.swift
> +import SwiftUI
스유?🤔

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/NoIconsView.swift
> +        addSubview(noIconsView)
nib에서 이니셜라이즈하는 코드 반복되고있는데, NibBased이런식으로 프로토콜 하나 빼볼까용?

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/OneIconView.swift
> +//    let selectIconModel: [SelectedIconButton]
사용 하나용?

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
혹시 이거 숫자 기준이 어떤걸까용?

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
>          }
오 이전보다 나은거같아 굳굳!!

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +//        self.viewModel.delegate = self
사용합니까~?

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    var viewModel: PostingViewModel = PostingViewModel()
이거 타입 추론 가능한데 명시할 필요 있을까용

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingViewModel.swift
>  class PostingViewModel {
final?😀

2022-07-27 15:18 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +//        window?.rootViewController = LocationAuthorizationViewController()
이거 확인하려고 수정했었나보넹! 근데 디벨롭에 머지는 하지 말아주세용~(삭제부탁드립니답!)
이제 플로우가 어느정도 완성이 돼서!
차라리 혜린이한테 홈에 버튼 하나 만들어서 리스트쪽으로 보내달라고 합시당
@hope1053

2022-07-29 03:14 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +//        window?.rootViewController = LocationAuthorizationViewController()
@lina0322 넴 확인 완료~ 만들어서 올리겠슴다

2022-07-29 03:16 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    var viewModel: PostingViewModel = PostingViewModel()
@lina0322 아무래도 린트를 죽여야.....🪚

2022-07-29 03:18 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    }
으아 스위프트 젠 쓰고싶다

2022-07-29 03:23 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/ManyIconsView.swift
> +import SwiftUI
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ갑분스유 혼자 스유 공부하고 계셨나요 ㄷㄷ

2022-07-29 03:24 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RoundLabel.swift
> +        self.layer.masksToBounds = true
@lina0322 ㅋㅋㅋㅋㅋㅋㅋㅇㄴㅋㅋㅋㄴ 찾아보겠습니다..

2022-07-29 03:25 UTC, hope1053 approved these changes
수고하셨으여~~~~👍

2022-07-29 16:20 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/NoIconsView.swift
> +        addSubview(noIconsView)
멘토님 코드를 참고해서 프로토콜화 시켜놓았습니다 ㅎㅎ

2022-07-29 16:20 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +//        self.viewModel.delegate = self
제거하겠습니다~~

2022-07-29 16:20 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    var viewModel: PostingViewModel = PostingViewModel()
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ린트 ㅋㅋㅋㅋㅋㅋ맞음 린트 떄매 저렇게 했어

2022-07-29 16:20 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +//        window?.rootViewController = LocationAuthorizationViewController()
알겠습니다!

2022-07-29 16:22 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    }
ㄹㅇ 젠 너무 그리워

2022-07-29 16:23 UTC, lina0322 commented
컨플릭낫다아아ㅏㅏ

2022-07-29 16:26 UTC, lina0322 approved these changes
이거는 다음 PR에 반영해주세용!

2022-07-29 16:26 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/ManyIconsView.swift
> +    @IBOutlet private var iconsImageViewCollection: [RotatableImageView]!
변수를 위로 올려주세용

2022-07-29 16:26 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostModel.swift
>  }
이거 파일 분리해주세욥!

2022-07-30 06:19 UTC, merged