Feature/list view
mash-up-kr/DamgleDamgle_iOS pull request #54
Opened 2022-08-08 06:55 UTC by cws653

## 이슈 링크
- 토스트 메세지 애니메이션과 이모지 애니메이션이 겹치면서 이모지 애니니메이션이 구현안되는 에러 발생

## 작업 내용
- 이모지 클릭시 토스트 메세지 뜨도록 구현

### 스크린샷
https://user-images.githubusercontent.com/45356844/183357383-5d38af20-fbcf-45a8-812e-9ae927d7611a.mp4

## To 리뷰어 (참고사항)
- 이모지 애니메이션이 깨지는 현상이 발생하고 있는데 원인 파악이 안되고 있습니다.

2022-08-09 15:32 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastLabel.swift
> +    internal func setupViewProperties() {
외부 모듈 쓰는게 아니면 디폴트가 internal이라 따로 명시안해줘도 된다고 알고 있슴다!

2022-08-09 15:33 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastView.swift
> +class ToastView: UIView, NibBased {
지금 View랑 Label을 따로 만든 것 같은데 하나의 xib에 다 포함시켜서 만들 수도 있지 않을까요~?

2022-08-10 09:47 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastView.swift
> +class ToastView: UIView, NibBased {
ToastView는 클래스는 삭제 했는데 포함되서 올라간 것 같습니다. 삭제해서 다시 커밋 푸쉬 해놓도록 하겠습니다!

2022-08-10 09:47 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastLabel.swift
> +    internal func setupViewProperties() {
옙 삭제하도록 하겠습니다!

2022-08-11 14:41 UTC, lina0322 requested changes
같은 리뷰가 반복되는 경우가 많아요~
커밋 전에, PR 전, PR 후에 스스로의 코드를 리뷰하는 시간을 가져주세요!
저희 서로의 코드를 리뷰 하는 일이 서로 숙제검사하고 답이 맞다 틀리다 하는 과정이 아니에요.
좀 더 좋은 앱, 좀 더 좋은 성능, 좀 더 좋은 코드를 구현하기 위해 서로 의견을 나누고
혹시라도 발생할 수 있는 에러를 미리 잡고자 하는 것입니다!!
이 부분 꼭 기억해주세요🙏

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/AppDelegate.swift
>          return true
커밋하기 전에, 또는 PR하면서 변경 사항 보고 필요한 수정인지 아닌지 확인하는 습관이 필요할거같아요!🙏
이렇게 파일이 섞여있으면 어? 이건 왜 수정됐지? 하는 것들이 간혹 함께 있네요~

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/LineSpacingLabel.swift
> +        let attrString = NSMutableAttributedString(string: text!)
강제 언래핑 하신거 변경해주세요~

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastLabel.swift
> +class ToastLabel: UILabel, NibBased {
final 필요할거같아욥

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastLabel.swift
> +    }
이거 둘 다 필요한거 맞죠??

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/ToastLabel/ToastLabel.swift
> +    func setupUI(text: String?) {
internal을 안 붙이는 습관으로 갑시다!

이거 차라리 함수 두 개 합쳐서 setupText가 낫지않을까 싶네용

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    }
비어있는 함수가 있네요~
사용할거라면 안에 TODO해주시고, 아니면 지워주세요!

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
> +    var toastMessageTitle: String? {
LGTM👍

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    }
cell 내부에서 draw하는거 대신 여기서 작업하는건가용?

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +            let cell = tableView.dequeueReusableCell(for: indexPath) as PostTableViewCell
이거는 왜 생성했을까용?🤔

2022-08-11 14:41 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +        window?.rootViewController = PostingNavigationController.instantiate()
이거 변경하지 말아주세요❗️❗️❗️❗️❗️

2022-08-16 13:19 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +    }
옙 해결방법을 찾다가 찾은 방법이 viewController의 layout이 잡힌 후에 호출되는 함수인 viewDidLayoutSubviews 에서 tableview를 reloadData 하는 것이었습니다.
cell안에서 해결할 수 있는 좀 더 세련된 방법이 있을 것 같은데 방법을 좀 더 찾아본 후 리팩토링해야할 것 같습니다..

2022-08-16 13:21 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +            let cell = tableView.dequeueReusableCell(for: indexPath) as PostTableViewCell
잘못 기입한 것 같습니다~~! 제외하도록 하겠습니다~~

2022-08-16 13:21 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +        window?.rootViewController = PostingNavigationController.instantiate()
ㅋㅋㅋㅋㅋㅋㅋ알겠습니다 ㅋㅋㅋㅋㅋㅋ !!! 에서 빡침이 느껴지네요 죄송합니다~~

2022-08-17 12:59 UTC, lina0322 approved these changes

2022-08-20 07:02 UTC, closed without merging