Feature/list view api
mash-up-kr/DamgleDamgle_iOS pull request #55
Opened 2022-08-11 04:47 UTC by cws653

## 이슈 링크
## 작업 내용
- ListView API 추가 -> 서버 작업이 추가로 이뤄져야 하므로, 작업 이후에 다시 손볼 예정
- ViewModel 적용
### 스크린샷
## To 리뷰어 (참고사항)
- 현재 서버 Response 값 수정이 있을 예정이라 수정 이후 적용이 될 항목은 TODO로 표현해놓았습니다.
- 코드 수정이 필요한 부분 알려주시면 반영하도록 하겠습니다!

2022-08-11 14:43 UTC, lina0322 requested changes
요거 base branch 확인해서 다시 PR 부탁드립니다.
이전 PR이랑 겹치는 내용이 있어요

2022-08-11 14:43 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/AppDelegate.swift
> +//        UINavigationBar.appearance().isTranslucent = false
확인해주세요~

2022-08-11 14:43 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/Contents.json
> +      "filename" : "btn_point@1x.pdf",
pdf랑 png랑 어떤 차이가 있는지 아시나용

2022-08-11 14:43 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/LineSpacingLabel.swift
> +    }
앞에 리뷰랑 동일한 코드가 보이는데욥..?!

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/StoryService.swift
> +                        print(error.localizedDescription)
print 어떻게 하라고했죠~?

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/StoryService.swift
> +    static func getMyStory(size: Int?, storyID: String?, completion: @escaping (Result<MyStoryResponse, Error>) -> Void) {
근데 왜 static이지????

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/StoryTarget.swift
자꾸 PR이 뭔가 겹치는거같은데...?

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewController.swift
>      }
함수로 빼주세요

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewModel.swift
>  class NicknameViewModel {
final~

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
> +        }
함수 분리!

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingViewModel.swift
> +                print(error)
print~

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/TestPostingViewModel.swift~feature/listView
> +
이 파일 왜이러지??? 모지 왜 허옇지
ㅍㅏ일 타입이 swift가 아닌데..?

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +        window?.rootViewController = PostingNavigationController.instantiate()
선생님~~~~

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/User/UserManager.swift
> +    private(set) var userNo: Int
줄바꿈 좀 해주세욥

2022-08-11 14:47 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/User/UserManager.swift
> +            return }
줄바꿈...!

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewController.swift
>      }
옙 알겠습니다~~

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewModel.swift
>  class NicknameViewModel {
옙 반영해놓겠습니다!

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingViewModel.swift
> +                print(error)
옙 반영해놓겠습니다~~

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/TestPostingViewModel.swift~feature/listView
> +
ㅋㅋㅋㅋㅋㅋ이거 파일 삭제한거라 그런듯요 ㅋㅋㅋ

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +        window?.rootViewController = PostingNavigationController.instantiate()
ㅋㅋㅋㅋㅋ죄송합니다 ㅋㅋㅋㅋ

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/User/UserManager.swift
> +    private(set) var userNo: Int
옙 알겠습니다

2022-08-16 14:25 UTC, cws653 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/User/UserManager.swift
> +            return }
옙 반영해놓도록 하겠습니다!

2022-08-17 13:01 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/LineSpacingLabel.swift
> +    }
`listview 브랜치를 기반으로 작성`하면 base 브랜치를 `listview 브랜치`로 해야하지 않을까요??

2022-08-17 13:02 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/StoryService.swift
> +    static func getMyStory(size: Int?, storyID: String?, completion: @escaping (Result<MyStoryResponse, Error>) -> Void) {
호출 편리성을 위해 static을 사용하는건 납득하기가 어렵네요! 🤔
다른 사람의 코드를 참고하더라도, 본인만의 기준이 필요할거같아요. 
이유가 따로 없다면 static 제거하는건 어떨까요?

2022-08-17 13:05 UTC, lina0322 commented
다시 확인 부탁드립니다~🙏

2022-08-17 15:06 UTC, hope1053 approved these changes

2022-08-17 15:06 UTC, lina0322 approved these changes

2022-08-17 15:08 UTC, merged