⚡ 신고하기 로직 구현
mash-up-kr/DamgleDamgle_iOS pull request #66
Opened 2022-08-22 16:21 UTC by cws653

## 작업 내용
- 신고하기 로직 구현 (API 및 Alert 메세지 구현)

2022-08-23 01:03 UTC, lina0322 requested changes

2022-08-23 01:03 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
> +        window?.rootViewController = PostingNavigationController.instantiate()
여기ㅣㅣㅣㅣㅣㅣㅣ

2022-08-23 16:22 UTC, hope1053 approved these changes

2022-08-24 01:14 UTC, lina0322 approved these changes

2022-08-24 01:14 UTC, merged