🚀 마커 추가
mash-up-kr/DamgleDamgle_iOS pull request #70
Opened 2022-08-25 15:55 UTC by hope1053

- 이슈 링크: #51 
## 작업 내용
- 클러스터링 로직 추가해서 마커 추가
- 마커 Struct 생성 후 각 데이터 CustomView에 반영 후 마커 이미지 변경 
## To 리뷰어 (참고사항)
위치 업데이트 잘 안되는 이슈 추후 수정 예정입니다,,

2022-08-25 16:07 UTC, lina0322 requested changes

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +            locationManager.startUpdatingCurrentLocation()
LGTM🥰

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +        DispatchQueue.main.async {
[weak self] 필요하지 않을까용?

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +                self.mapViewMarkerList = []
forEach하는 배열을 빈배열로 만드는거 맞나용?

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +                    self?.present(postingMainNavigationViewController, animated: true)
여기 함수로 분리하는게 더 깔끔할거같습니답. 함수가 너무 덩어리가 커지고이씀다!

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +    @IBAction func paintViewDidTap(_ sender: UITapGestureRecognizer) {
private 일거같네용~

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +        currentLocationMarker.zIndex = -100
이건 관계없나? -100은 뭐때문인지 모르겠어섭!

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +            self.viewModel.getStoryFeed { result in
네트워크 통신쪽에는 되도록 항상 weak self 넣어주세용

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewModel.swift
> +            let haveMyStory = storyList.filter { $0.isMine == true }.count > 0
has로 해주면 안되남ㅎㅎ...

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.swift
> +        UIView.animate(withDuration: 0.3, delay: 0, options: .curveEaseIn) { [weak self] in
`delay: 0` 파라매터 아예 빼도 될거에유
options 따로 curveEaseIn으로 설정한 이유 있나요? 보통 easy inout 쓰더라고욥

2022-08-25 16:07 UTC, lina0322 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewModel.swift
> +            address1: locationService.currentAddress[0],
index safe하게 접근해주세용. array에 safe extension 해둔거같아용

2022-08-25 16:23 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Custom/CustomMarker/CustomMarker.swift
> +    }
@lina0322 넴 !

2022-08-25 16:29 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +        currentLocationMarker.zIndex = -100
@lina0322 현재 내 위치 마커랑 내 글 마커 겹치는 경우에 내 글 마커를 위에 표시해줘야돼서 위치 마커 zIndex를 마이너스값을 줬습니도ㅏ,,,!

2022-08-25 16:30 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +            self.viewModel.getStoryFeed { result in
@lina0322 이거는 카메라 위치 업데이트 해주는거라서 네트워크 통신이 아닐지도..! 그럴지도...! 말씀해주신 부분은 명심하겠습니닷.

2022-08-25 16:32 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.swift
> +        UIView.animate(withDuration: 0.3, delay: 0, options: .curveEaseIn) { [weak self] in
@lina0322 delay는 삭제하면 파라미터 빠졌다고 에러가 뜨는데.....ㅜ_ㅜ 
아녀 그냥 테스트해보다가 그게 자연스러워보여서 했는뎅 easeInOut을 보통 쓰는줄 몰랐네요! 참고하겠습니당~

2022-08-26 02:08 UTC, lina0322 approved these changes

2022-08-26 02:18 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +                self.mapViewMarkerList = []
@lina0322 앗 실수..

2022-08-26 02:18 UTC, hope1053 commented on DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
> +                    self?.present(postingMainNavigationViewController, animated: true)
@lina0322 헷..급하게하느라..수정하게씀다 !

2022-08-26 02:30 UTC, merged